[2024-01-08T19:49:23.405+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Local_Data_Ingestion.ingest scheduled__2023-01-02T07:00:00+00:00 [queued]>
[2024-01-08T19:49:23.420+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Local_Data_Ingestion.ingest scheduled__2023-01-02T07:00:00+00:00 [queued]>
[2024-01-08T19:49:23.420+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 3
[2024-01-08T19:49:23.756+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): ingest> on 2023-01-02 07:00:00+00:00
[2024-01-08T19:49:23.766+0000] {standard_task_runner.py:60} INFO - Started process 883 to run task
[2024-01-08T19:49:23.778+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Local_Data_Ingestion', 'ingest', 'scheduled__2023-01-02T07:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpj4jhhkcv']
[2024-01-08T19:49:23.786+0000] {standard_task_runner.py:88} INFO - Job 89: Subtask ingest
[2024-01-08T19:49:23.886+0000] {task_command.py:423} INFO - Running <TaskInstance: Local_Data_Ingestion.ingest scheduled__2023-01-02T07:00:00+00:00 [running]> on host 7374efdae9b6
[2024-01-08T19:49:23.965+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-01-08T19:49:24.026+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Local_Data_Ingestion' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T07:00:00+00:00'
[2024-01-08T19:49:24.029+0000] {logging_mixin.py:188} INFO - yellow_tripdata_2023_01 /opt/***/input_2023-01.parquet
[2024-01-08T19:49:25.150+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_script.py", line 9, in data_ingest
    parquet_data = pd.read_parquet(file)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/input_2023-01.parquet'
[2024-01-08T19:49:25.164+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Local_Data_Ingestion, task_id=ingest, execution_date=20230102T070000, start_date=20240108T194923, end_date=20240108T194925
[2024-01-08T19:49:25.200+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 89 for task ingest ([Errno 2] No such file or directory: '/opt/airflow/input_2023-01.parquet'; 883)
[2024-01-08T19:49:25.238+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T19:49:25.264+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
